### ISSUE TITLE
Algolia index not updating fields changed to null value.

### ISSUE THREAD

**Issue by devaaronc** [algolia/firestore-algolia-search#61] opened 2021-09-05 23:56 UTC
When I update a field value within a Firestore document to null, the extension executes, but does not actually update the value in the Algolia index. I would assume the Algolia value would be deleted from the index, as null values are not transferred from Firestore to Algolia.

**Comment by smomin** [comment] 2021-09-10 16:14
Currently this is not possible with the approach I have taken.  I am thinking through an approach that will clean up null attributes.  Will update when I have a solution.

**Comment by smomin** [comment] 2021-09-10 16:15
How often are you setting attributes to null?  Can you send me examples so I can see if there are alternative solutions I can think through?

**Comment by devaaronc** [comment] 2021-09-11 07:35
The attributes aren't set to null very often. Example: a document may have an attribute that was mistakenly given a value (by a user), so it is later corrected to null.

**Comment by Haroenv** [comment] 2021-09-13 07:46
https://discourse.algolia.com/t/deleting-attributes-in-partial-updates/10154 I think we might be better off updating the objects altogether instead of partially updating. It doesn't have a difference in cost and will solve this issue. Deleting objects alltogether isn't solved by just swapping partialUpdate to save though

**Comment by Haroenv** [comment] 2021-09-13 07:47
this issue is a duplicate of #60

**Comment by smomin** [comment] 2021-09-13 16:33
@Haroenv The partialUpdate was used to manage race conditions that could occur from the cold start up of the Cloud functions.  Before this approach, I had an extra call to the Firestore db to sync up the records after then Cloud Function was warmed up, but this would be a Firestore cost.

I am currently considering looping through the payload for null values.  If I encounter any fields with null values, i will use the saveObject method.  However, I will have to make a call to Firestore db to refresh the data just in case if the data has changed.

**Closed** 2021-09-14 07:30 UTC

**Comment by saifxx** [comment] 2021-09-23 09:10
> @Haroenv The partialUpdate was used to manage race conditions that could occur from the cold start up of the Cloud functions. Before this approach, I had an extra call to the Firestore db to sync up the records after then Cloud Function was warmed up, but this would be a Firestore cost.
> 
> I am currently considering looping through the payload for null values. If I encounter any fields with null values, i will use the saveObject method. However, I will have to make a call to Firestore db to refresh the data just in case if the data has changed.

Ok but what if someone uses _'firebase.firestore.FieldValue.delete()'_ to remove the field?
