### ISSUE TITLE
Prematurely Exiting Full Indexing

### ISSUE THREAD

**Issue by LucasSwitz** [algolia/firestore-algolia-search#189] opened 2023-12-06 16:04 UTC
I was using this extension to index a couple hundred thousand documents from Firestore. The indexing job stopped after indexing around 20% of the documents.

Looks like the firestore query returned more documents then was requested by limit(DOCS_PER_INDEXING) 🤷. Because of this, the termination condition triggered and the job ended. 

I attached a log showing records.length > DOCS_PER_INDEXING.

I think this can be fixed by just changing the termination condition to records.length < DOCS_PER_INDEXING.

[downloaded-logs-20231206-104844.json](https://github.com/algolia/firestore-algolia-search/files/13588319/downloaded-logs-20231206-104844.json)

**Comment by smomin** [comment] 2023-12-10 05:37
hey @LucasSwitz  how many documents are you trying to index?  check with Algolia support to make sure your Algolia application is under the right plan.

**Comment by smomin** [comment] 2023-12-15 17:24
@LucasSwitz The extension v1.2.0 has been approved.  Can you check to see if you are running into the same issues.

**Comment by smomin** [comment] 2024-01-04 05:17
I am closing this issue since I have not heard further comments.  I will assume the issue is resolved.

**Closed by smomin** 2024-01-04 05:17 UTC
